/**
 * The starting collection a new reader sees, ported from server/Data/SeedData.cs.
 * Dates stay relative to today so the shelf never looks stale.
 */

import { daysAgo, type Bookshelf, type ReadingStatus, type StoredBook } from './domain'

type SeedBook = {
  id: string
  title: string
  author: string
  genre: string
  pageCount: number
  status: ReadingStatus
  blurb: string
  moods: string[]
  coverPalette: string
  addedDaysAgo: number
  currentPage?: number
  startedDaysAgo?: number
  finishedDaysAgo?: number
  rating?: number
}

const SEED_BOOKS: SeedBook[] = [
  // ---------- Currently reading ----------
  {
    id: 'overstory',
    title: 'The Overstory',
    author: 'Richard Powers',
    genre: 'Literary Fiction',
    pageCount: 502,
    status: 'CurrentlyReading',
    currentPage: 214,
    blurb: 'Nine strangers are drawn together by the trees that outlive them.',
    moods: ['sweeping', 'thought-provoking'],
    coverPalette: 'moss',
    addedDaysAgo: 96,
    startedDaysAgo: 31,
  },
  {
    id: 'sweetgrass',
    title: 'Braiding Sweetgrass',
    author: 'Robin Wall Kimmerer',
    genre: 'Nature Writing',
    pageCount: 390,
    status: 'CurrentlyReading',
    currentPage: 88,
    blurb: 'A botanist braids together Indigenous wisdom and plant science.',
    moods: ['quiet', 'hopeful'],
    coverPalette: 'sage',
    addedDaysAgo: 140,
    startedDaysAgo: 12,
  },

  // ---------- Want to read ----------
  {
    id: 'piranesi',
    title: 'Piranesi',
    author: 'Susanna Clarke',
    genre: 'Fantasy',
    pageCount: 245,
    status: 'WantToRead',
    blurb: 'A man keeps careful notes on the endless halls of the House he lives in.',
    moods: ['quiet', 'twisty'],
    coverPalette: 'indigo',
    addedDaysAgo: 58,
  },
  {
    id: 'remains-day',
    title: 'The Remains of the Day',
    author: 'Kazuo Ishiguro',
    genre: 'Literary Fiction',
    pageCount: 258,
    status: 'WantToRead',
    blurb: 'An English butler retraces a lifetime of small, careful choices.',
    moods: ['quiet', 'tender'],
    coverPalette: 'sand',
    addedDaysAgo: 210,
  },
  {
    id: 'klara',
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    genre: 'Science Fiction',
    pageCount: 303,
    status: 'WantToRead',
    blurb: 'An artificial friend watches the family she hopes will choose her.',
    moods: ['tender', 'thought-provoking'],
    coverPalette: 'amber',
    addedDaysAgo: 44,
  },
  {
    id: 'tomorrow',
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    author: 'Gabrielle Zevin',
    genre: 'Contemporary Fiction',
    pageCount: 401,
    status: 'WantToRead',
    blurb: 'Two friends spend thirty years building games and missing each other.',
    moods: ['immersive', 'tender'],
    coverPalette: 'teal',
    addedDaysAgo: 27,
  },
  {
    id: 'thursday-club',
    title: 'The Thursday Murder Club',
    author: 'Richard Osman',
    genre: 'Mystery',
    pageCount: 382,
    status: 'WantToRead',
    blurb: 'Four retirees meet weekly to solve cold cases, then get a warm one.',
    moods: ['funny', 'twisty'],
    coverPalette: 'rust',
    addedDaysAgo: 19,
  },
  {
    id: 'gentleman-moscow',
    title: 'A Gentleman in Moscow',
    author: 'Amor Towles',
    genre: 'Historical Fiction',
    pageCount: 462,
    status: 'WantToRead',
    blurb: 'A count is sentenced to house arrest in a grand hotel for thirty years.',
    moods: ['cozy', 'sweeping'],
    coverPalette: 'plum',
    addedDaysAgo: 163,
  },
  {
    id: 'sea-tranquility',
    title: 'Sea of Tranquility',
    author: 'Emily St. John Mandel',
    genre: 'Science Fiction',
    pageCount: 255,
    status: 'WantToRead',
    blurb: 'A strange note of music repeats across five centuries.',
    moods: ['quiet', 'twisty'],
    coverPalette: 'slate',
    addedDaysAgo: 9,
  },
  {
    id: 'educated',
    title: 'Educated',
    author: 'Tara Westover',
    genre: 'Memoir',
    pageCount: 334,
    status: 'WantToRead',
    blurb: 'A woman raised off the grid in Idaho teaches herself all the way to Cambridge.',
    moods: ['unsettling', 'thought-provoking'],
    coverPalette: 'clay',
    addedDaysAgo: 122,
  },
  {
    id: 'convenience-store',
    title: 'Convenience Store Woman',
    author: 'Sayaka Murata',
    genre: 'Literary Fiction',
    pageCount: 163,
    status: 'WantToRead',
    blurb:
      'Keiko has worked the same shop for eighteen years and would like everyone to stop asking why.',
    moods: ['funny', 'unsettling'],
    coverPalette: 'ink',
    addedDaysAgo: 73,
  },
  {
    id: 'thinking-systems',
    title: 'Thinking in Systems',
    author: 'Donella H. Meadows',
    genre: 'Nonfiction',
    pageCount: 240,
    status: 'WantToRead',
    blurb: 'A primer on why complicated problems push back when you poke them.',
    moods: ['brainy', 'thought-provoking'],
    coverPalette: 'cocoa',
    addedDaysAgo: 35,
  },
  {
    id: 'cerulean-sea',
    title: 'The House in the Cerulean Sea',
    author: 'TJ Klune',
    genre: 'Fantasy',
    pageCount: 396,
    status: 'WantToRead',
    blurb: 'A by-the-book caseworker is sent to inspect an orphanage of magical children.',
    moods: ['cozy', 'hopeful'],
    coverPalette: 'teal',
    addedDaysAgo: 51,
  },
  {
    id: 'hobbit',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    pageCount: 310,
    status: 'WantToRead',
    blurb: 'A comfortable hobbit is talked into an extremely uncomfortable adventure.',
    moods: ['adventurous', 'cozy'],
    coverPalette: 'moss',
    addedDaysAgo: 365,
  },

  // ---------- Finished ----------
  {
    id: 'hail-mary',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    genre: 'Science Fiction',
    pageCount: 476,
    status: 'Finished',
    currentPage: 476,
    rating: 5,
    blurb: 'A lone astronaut wakes with amnesia and one chance to save the sun.',
    moods: ['adventurous', 'brainy'],
    coverPalette: 'amber',
    addedDaysAgo: 260,
    startedDaysAgo: 78,
    finishedDaysAgo: 64,
  },
  {
    id: 'circe',
    title: 'Circe',
    author: 'Madeline Miller',
    genre: 'Mythology',
    pageCount: 393,
    status: 'Finished',
    currentPage: 393,
    rating: 5,
    blurb: 'The witch of Aiaia tells her own version of the myth.',
    moods: ['sweeping', 'immersive'],
    coverPalette: 'plum',
    addedDaysAgo: 300,
    startedDaysAgo: 118,
    finishedDaysAgo: 99,
  },
  {
    id: 'station-eleven',
    title: 'Station Eleven',
    author: 'Emily St. John Mandel',
    genre: 'Science Fiction',
    pageCount: 333,
    status: 'Finished',
    currentPage: 333,
    rating: 5,
    blurb: 'A travelling symphony keeps Shakespeare alive after the world ends.',
    moods: ['quiet', 'hopeful'],
    coverPalette: 'slate',
    addedDaysAgo: 330,
    startedDaysAgo: 155,
    finishedDaysAgo: 139,
  },
  {
    id: 'night-circus',
    title: 'The Night Circus',
    author: 'Erin Morgenstern',
    genre: 'Fantasy',
    pageCount: 387,
    status: 'Finished',
    currentPage: 387,
    rating: 4,
    blurb:
      'Two magicians are bound to a duel staged inside a circus that opens at nightfall.',
    moods: ['immersive', 'cozy'],
    coverPalette: 'ink',
    addedDaysAgo: 280,
    startedDaysAgo: 196,
    finishedDaysAgo: 175,
  },
  {
    id: 'never-let-me-go',
    title: 'Never Let Me Go',
    author: 'Kazuo Ishiguro',
    genre: 'Literary Fiction',
    pageCount: 288,
    status: 'Finished',
    currentPage: 288,
    rating: 5,
    blurb: 'Three friends slowly understand what their boarding school was for.',
    moods: ['quiet', 'unsettling'],
    coverPalette: 'sand',
    addedDaysAgo: 240,
    startedDaysAgo: 228,
    finishedDaysAgo: 214,
  },
  {
    id: 'anxious-people',
    title: 'Anxious People',
    author: 'Fredrik Backman',
    genre: 'Contemporary Fiction',
    pageCount: 342,
    status: 'Finished',
    currentPage: 342,
    rating: 4,
    blurb: "A failed bank robbery turns into the world's most forgiving hostage situation.",
    moods: ['funny', 'tender'],
    coverPalette: 'rust',
    addedDaysAgo: 190,
    startedDaysAgo: 44,
    finishedDaysAgo: 33,
  },
  {
    id: 'midnight-library',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    genre: 'Contemporary Fiction',
    pageCount: 288,
    status: 'Finished',
    currentPage: 288,
    rating: 3,
    blurb: "Between life and death is a library of every life you didn't live.",
    moods: ['hopeful', 'thought-provoking'],
    coverPalette: 'indigo',
    addedDaysAgo: 150,
    startedDaysAgo: 21,
    finishedDaysAgo: 14,
  },
]

function toStoredBook(seed: SeedBook): StoredBook {
  return {
    id: seed.id,
    title: seed.title,
    author: seed.author,
    genre: seed.genre,
    pageCount: seed.pageCount,
    status: seed.status,
    currentPage: seed.currentPage ?? 0,
    blurb: seed.blurb,
    moods: seed.moods,
    coverPalette: seed.coverPalette,
    dateAdded: daysAgo(seed.addedDaysAgo),
    dateStarted: seed.startedDaysAgo === undefined ? null : daysAgo(seed.startedDaysAgo),
    dateFinished: seed.finishedDaysAgo === undefined ? null : daysAgo(seed.finishedDaysAgo),
    rating: seed.rating ?? null,
    lastSkippedAt: null,
  }
}

export function createBookshelf(): Bookshelf {
  return {
    readerName: 'Ethan',
    goal: { year: new Date().getFullYear(), targetBooks: 20 },
    books: SEED_BOOKS.map(toStoredBook),
  }
}
